export const CREATE_BOOKING_REQUEST = 'cinema/CREATE_BOOKING_REQUEST';
export type CREATE_BOOKING_REQUEST = typeof CREATE_BOOKING_REQUEST;

export const CREATE_BOOKING_SUCCESS = 'cinema/CREATE_BOOKING_SUCCESS';
export type CREATE_BOOKING_SUCCESS = typeof CREATE_BOOKING_SUCCESS;

export const CREATE_BOOKING_FAILURE = 'cinema/CREATE_BOOKING_FAILURE';
export type CREATE_BOOKING_FAILURE = typeof CREATE_BOOKING_FAILURE;
