export const REGISTER_REQUEST = "cinema/REGISTER_REQUEST"
export type REGISTER_REQUEST = typeof REGISTER_REQUEST

export const REGISTER_SUCCESS = "cinema/REGISTER_SUCCESS"
export type REGISTER_SUCCESS = typeof REGISTER_SUCCESS

export const REGISTER_FAILURE = "cinema/REGISTER_FAILURE"
export type REGISTER_FAILURE = typeof REGISTER_FAILURE

export const LOGIN_REQUEST = "cinema/LOGIN_REQUEST"
export type LOGIN_REQUEST = typeof LOGIN_REQUEST

export const LOGIN_SUCCESS = "cinema/LOGIN_SUCCESS"
export type LOGIN_SUCCESS = typeof LOGIN_SUCCESS

export const LOGIN_FAILURE = "cinema/LOGIN_FAILURE"
export type LOGIN_FAILURE = typeof LOGIN_FAILURE
